In [1]:
from glob import glob

filenames = sorted(list(glob('npzfiles/*.npz')))

In [2]:
import numpy as np
from simulations.concentrations.MLE import get_NB_score_function

from scipy.optimize import root_scalar

In [3]:
from analysis_utils.concentrations_MLE import get_NB_MLE

In [4]:
get_NB_MLE(filenames[0])

0

In [5]:
npzfile = np.load('concentration_ML_estimates/simulation.001.density.npz')

In [6]:
npzfile['whole_sim']

array([126.74787036])

In [7]:
npzfile['medium_batches']

array([186.79630488,   9.12992535,          inf,          inf,
                inf,   8.30082266,  12.43585769,  34.05391735,
        42.08646906,          inf,          inf,          inf,
                inf, 162.52222691,   9.18283852,          inf,
         6.93175344,          inf,  27.23539741,   5.39385777,
         6.44678786,          inf,          inf,  10.85755463,
         6.16239744,          inf,   7.80802758,  64.44637611,
                inf,          inf])

In [8]:
npzfile['small_batches']

array([ 3.44956953,  1.06134458,         inf, ..., 18.23784568,
               inf,         inf])

## Example

In [9]:
npzfile = np.load(filenames[0])
droplets = npzfile['droplets']

counts = np.sum(droplets, axis=1)
mean_count = np.mean(counts)
number_droplets, number_strains = droplets.shape

score_function = get_NB_score_function(counts, mean_count, number_droplets, number_strains)

In [10]:
from scipy.optimize import fsolve

`fsolve` more general framework/wrapper, but seem to get better results using more 'targeted' options

In [11]:
fsolve(score_function, 200, full_output=True)

(array([200.00545969]),
 {'nfev': 14,
  'fjac': array([[-1.]]),
  'r': array([1.05772255e-05]),
  'qtf': array([2.87526132e-06]),
  'fvec': array([-2.87526132e-06])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [12]:
root_scalar(f=score_function, x0=200, bracket=(0.00001,100000))

      converged: True
           flag: 'converged'
 function_calls: 6
     iterations: 5
           root: 99999.99996164694

In [13]:
fsolve(score_function, 100, full_output=True)

(array([126.74064385]),
 {'nfev': 22,
  'fjac': array([[-1.]]),
  'r': array([20.5390162]),
  'qtf': array([-1.58706825e-10]),
  'fvec': array([0.])},
 1,
 'The solution converged.')

In [14]:
fsolve(score_function, 50, full_output=True)

(array([126.75049318]),
 {'nfev': 43,
  'fjac': array([[-1.]]),
  'r': array([6.53390215]),
  'qtf': array([-4.10636858e-10]),
  'fvec': array([4.10636858e-10])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [15]:
fsolve(score_function, 150, full_output=True)

(array([150.00643944]),
 {'nfev': 16,
  'fjac': array([[-1.]]),
  'r': array([0.00036213]),
  'qtf': array([2.16380749e-06]),
  'fvec': array([-2.16380749e-06])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [16]:
fsolve(score_function, 175, full_output=True)

(array([126.73480219]),
 {'nfev': 21,
  'fjac': array([[-1.]]),
  'r': array([20.52486078]),
  'qtf': array([-4.45652404e-11]),
  'fvec': array([4.54747351e-13])},
 1,
 'The solution converged.')

In [17]:
root_scalar(f=score_function, x0=175, bracket=(0.0001,10000))

      converged: True
           flag: 'converged'
 function_calls: 47
     iterations: 46
           root: 126.74787035600554

In [18]:
fsolve(score_function, 160, full_output=True)

(array([159.96490917]),
 {'nfev': 14,
  'fjac': array([[-1.]]),
  'r': array([8.53543945e-06]),
  'qtf': array([2.5480922e-06]),
  'fvec': array([-2.5480922e-06])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [19]:
root_scalar(f=score_function, x0=160, bracket=(0.0001,10000))

      converged: True
           flag: 'converged'
 function_calls: 47
     iterations: 46
           root: 126.74787035600554

In [20]:
fsolve(score_function, 155, full_output=True)

(array([155.00149942]),
 {'nfev': 14,
  'fjac': array([[-1.]]),
  'r': array([0.00056231]),
  'qtf': array([2.38226039e-06]),
  'fvec': array([-2.38226039e-06])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [21]:
root_scalar(f=score_function, x0=155, bracket=(0.0001,10000))

      converged: True
           flag: 'converged'
 function_calls: 47
     iterations: 46
           root: 126.74787035600554

In [22]:
fsolve(score_function, 150, full_output=True)

(array([150.00643944]),
 {'nfev': 16,
  'fjac': array([[-1.]]),
  'r': array([0.00036213]),
  'qtf': array([2.16380749e-06]),
  'fvec': array([-2.16380749e-06])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

#### score function evaluated at some values

In [23]:
score_function(50)

0.00019269783661002293

In [24]:
score_function(75)

3.851083056360949e-05

In [25]:
score_function(80)

2.8667676815530285e-05

In [26]:
score_function(90)

1.5826149137865286e-05

In [27]:
score_function(95)

1.1626661944319494e-05

In [28]:
score_function(97.5)

9.906954346661223e-06

In [29]:
score_function(100)

8.397984856856056e-06

In [30]:
score_function(100.10625)

8.33876720207627e-06

In [31]:
score_function(100.3125)

8.223453278333182e-06

In [32]:
score_function(100.625)

8.049932148423977e-06

In [33]:
score_function(101.25)

7.712331807852024e-06

In [34]:
score_function(102.5)

7.0697092269256245e-06

In [35]:
score_function(105)

5.899938514630776e-06

In [36]:
score_function(110)

3.951710823457688e-06

In [37]:
score_function(120)

1.2262821655895095e-06

In [38]:
score_function(200)

-2.8767808544216678e-06

In [39]:
score_function(2000)

-7.193975193331426e-08

In [40]:
score_function(20000)

-2.8414959274414286e-10

In [41]:
score_function(200000)

-6.243441319497833e-10

In [42]:
score_function(2000000)

1.603606580857786e-09

## Does this really work in general?

In [43]:
get_NB_MLE(filenames[17])

0

In [44]:
npzfile = np.load('concentration_ML_estimates/simulation.018.density.npz')

In [45]:
npzfile['whole_sim']

array([545.35721689])

In [46]:
npzfile['medium_batches']

array([         inf,  26.43459425,          inf,  21.57508205,
                inf, 523.90618372,  12.24311747,          inf,
         6.00458604,  50.26284676,   9.23863498,          inf,
         5.89499579,  14.8264288 ,          inf,          inf,
        39.67272374,          inf,  27.99066335,          inf,
                inf,  43.73626434,   7.3122151 ,          inf,
        16.0064103 ,  10.93401719,          inf,          inf,
                inf,          inf])

In [47]:
npzfile['small_batches']

array([2.25665464, 1.64237855,        inf, ..., 2.59803526, 1.30982057,
              inf])