In [1]:
import numpy as np
from simulations import dropletSimulation


In [2]:
def random_frequency_vector(length):
    unnormalized = np.random.randint(low=0, high=370, size=length)
    return unnormalized / sum(unnormalized)

def random_copy_numbers(length):
    return np.random.randint(low=1, high=16, size=length)

A = 2*(np.random.random((100,100)) - 0.5)
beta = np.random.random(100)

simulation = dropletSimulation(number_species=100, number_droplets=1000, number_batches=5, 
             copy_numbers=random_copy_numbers(100), frequency_vector=random_frequency_vector(100),
             glv_interaction_coefficients=A, glv_baserate_coefficients=beta, noise_scale=2, seed=42)

In [3]:
simulation.carrying_capacity

10000.0

In [4]:
simulation.poisson_rate

2.0

In [5]:
simulation.seed

SeedSequence(
    entropy=42,
)

In [6]:
simulation.timestep

0.01

In [7]:
simulation.cells

AttributeError: Please first use the `run_simulation` method in order to access the `cells` attribute

In [8]:
simulation.reads

AttributeError: Please first use the `run_simulation` method in order to access the `reads` attribute

In [9]:
simulation2 = dropletSimulation(number_species=100, number_droplets=1000, number_batches=5, 
             copy_numbers=random_copy_numbers(100), frequency_vector=random_frequency_vector(100),
             glv_interaction_coefficients=A, glv_baserate_coefficients=beta, noise_scale=2,
                               timestep = 0.001, batch_window=20)

In [10]:
%%time
simulation.run_simulation()

CPU times: user 1.28 s, sys: 528 ms, total: 1.81 s
Wall time: 2.28 s


In [11]:
%%time
simulation2.run_simulation()

CPU times: user 1.24 s, sys: 515 ms, total: 1.76 s
Wall time: 7.41 s


In [12]:
np.max(simulation2.cells.counts)

61566.61296742062

In [13]:
np.max(simulation.cells.counts)

59888213951256.84

In [14]:
simulation3 = dropletSimulation(number_species=100, number_droplets=1000, number_batches=5, 
             copy_numbers=random_copy_numbers(100), frequency_vector=random_frequency_vector(100),
             glv_interaction_coefficients=A, glv_baserate_coefficients=beta, noise_scale=2,
                               timestep = 0.0001, batch_window=200)

In [15]:
%%time
simulation3.run_simulation()

CPU times: user 1.23 s, sys: 529 ms, total: 1.76 s
Wall time: 1min 1s


In [16]:
np.sum(simulation.reads.counts >= 10000)

1725

In [17]:
np.sum(simulation.reads.counts >= 100000)

927

In [18]:
np.sum(simulation.cells.counts >= 10000)

397

In [19]:
np.sum(simulation.cells.counts >= 100000)

200

In [20]:
np.sum(simulation.cells.counts >= 1000000)

107

In [21]:
np.sum(simulation.cells.counts >= 100000000)

31

In [22]:
np.sum(simulation.cells.counts >= 100000000000)

6

In [23]:
np.sum(simulation.cells.counts < np.inf)

500000

In [24]:
np.sum(simulation.cells[...,2] >= 10000)

287

In [25]:
np.sum(simulation.cells[...,0] >= 10000)

0

In [26]:
np.sum(simulation.cells[...,1] >= 10000)

0

In [27]:
np.sum(simulation.cells[...,2] >= 10000)

287

In [28]:
np.sum(simulation.cells[...,3] >= 10000)

91

In [29]:
np.sum(simulation.cells[...,4] >= 10000)

19

ok kind of looks like things are getting smaller

In [30]:
np.sum(simulation.reads[...,0] >= 10000)

0

In [31]:
np.sum(simulation.reads[...,1] >= 10000)

0

In [32]:
np.sum(simulation.reads[...,2] >= 10000)

289

In [33]:
np.sum(simulation.reads[...,3] >= 10000)

665

In [34]:
np.sum(simulation.reads[...,4] >= 10000)

771

yeah number gets larger with each batch, for reads, again, makes sense

In [35]:
np.sum(simulation.reads.counts >= simulation.cells.counts)

500000

also perfect yay

In [36]:
%%time
simulation.reads.group_droplets()

CPU times: user 913 ms, sys: 28.1 ms, total: 941 ms
Wall time: 1.08 s


In [37]:
simulation.reads.get_fitness_coefficients(experiment_type="picky",
                                           control_type="picky")

array([[[0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,    

In [38]:
simulation.cells.get_fitness_coefficients(experiment_type="picky",
                                           control_type="picky")

AttributeError: Please first use the `group_droplets` method in order to access the `experiments` attribute

In [39]:
%%time
simulation.cells.group_droplets()

CPU times: user 445 ms, sys: 15.7 ms, total: 460 ms
Wall time: 460 ms


In [40]:
simulation.cells.get_fitness_coefficients(experiment_type="picky",
                                           control_type="picky")

array([[[0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,    

In [41]:
simulation.cells.get_fitness_coefficients()

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan],
        ...,
        [            nan,             nan,             nan,
                     nan,             nan],
        [ 3.30028653e-02,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan]],

       [[            nan,             nan,             nan,
                     nan,             nan],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,  8.29583049e-02,             nan,
                     nan,             nan],
        ...,
        [            nan,           

In [42]:
simulation.cells.get_fitness_coefficients(method="arithmetic",
                                           experiment_type="picky",
                                           control_type="picky")

array([[[0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,    

In [43]:
simulation.cells.get_fitness_coefficients(method="arithmetic")

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan],
        ...,
        [            nan,             nan,             nan,
                     nan,             nan],
        [ 2.47209306e-02,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan]],

       [[            nan,             nan,             nan,
                     nan,             nan],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,  4.30438813e-02,             nan,
                     nan,             nan],
        ...,
        [            nan,           

In [44]:
simulation.reads.get_fitness_coefficients(method="arithmetic",
                                           experiment_type="picky",
                                           control_type="picky")

array([[[0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [0.        , 0.        , 0.        , 0.        , 0.        ],
        [       nan,        nan,        nan,        nan,        nan],
        ...,
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,        nan]],

       [[       nan,        nan,        nan,        nan,        nan],
        [       nan,        nan,        nan,        nan,    

In [45]:
simulation.reads.get_fitness_coefficients(method="arithmetic")

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan],
        ...,
        [            nan,             nan,             nan,
                     nan,             nan],
        [ 2.47209306e-02,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan]],

       [[            nan,             nan,             nan,
                     nan,             nan],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,  4.30438813e-02,             nan,
                     nan,             nan],
        ...,
        [            nan,           

In [46]:
simulation.reads.get_fitness_coefficients()

array([[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan],
        ...,
        [            nan,             nan,             nan,
                     nan,             nan],
        [ 3.30028653e-02,             nan,             nan,
                     nan,             nan],
        [            nan,             nan,             nan,
                     nan,             nan]],

       [[            nan,             nan,             nan,
                     nan,             nan],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00],
        [            nan,  8.29583049e-02,             nan,
                     nan,             nan],
        ...,
        [            nan,           

In [47]:
simulation.reads.get_glv_coefficients()

{'interaction_estimates': array([[ 1.19798732e-01, -2.08826911e-17,  1.82769671e-16, ...,
          7.66379377e-18,  4.82510378e-02,  4.11239726e-18],
        [-2.63112254e-18,  5.72433542e-02, -3.11069888e-02, ...,
         -7.39135603e-03, -1.99670442e-01, -2.47586403e-03],
        [-8.94031530e-20, -7.22939395e-03,  1.44910523e-01, ...,
         -1.82785457e-03, -1.03865774e-01,  3.24040415e-02],
        ...,
        [ 0.00000000e+00,  5.30745998e-07, -1.35225019e-07, ...,
          1.10030275e-01,  0.00000000e+00,  0.00000000e+00],
        [ 4.77540384e-02, -2.94774599e-02, -1.76452880e-01, ...,
          0.00000000e+00,  1.40698263e-01,  2.95089595e-02],
        [ 0.00000000e+00,  1.03914854e-08,  4.06438704e-02, ...,
          0.00000000e+00,  4.55397383e-02,  1.48386675e-01]]),
 'baserate_estimates': array([0.07476729, 0.08097157, 0.09201362, 0.02997802, 0.34648813,
        0.09602626, 0.15349326, 0.0229557 ,        nan, 0.22031735,
        0.30300994, 0.03924007, 0.12048203, 0.

In [48]:
simulation.reads.get_glv_coefficients()["baserate_estimates"].shape

(100,)

In [49]:
simulation.reads.get_glv_coefficients()["interaction_estimates"].shape

(100, 100)

In [50]:
simulation.cells.get_glv_coefficients()["baserate_estimates"]

array([0.07412994, 0.0779769 , 0.10083486, 0.02997802, 0.26970923,
       0.09423176, 0.16638644, 0.07668644,        nan, 0.22697865,
       0.13050376, 0.05338868, 0.12466896, 0.08423594, 0.16224147,
       0.08170265, 0.19267174, 0.38341108, 0.10402755, 0.1046653 ,
       0.16206862, 0.1303954 , 0.27633365, 0.10127224, 0.21284622,
       0.14209093, 0.37701328, 0.18544763, 0.02017218,        nan,
       0.17699887,        nan, 0.26580757, 0.14433066, 0.26509764,
       0.19658563, 0.42886014, 0.077062  , 0.04082426, 0.07831543,
       0.10495104, 0.12604122, 0.34890479, 0.21967299, 0.16779612,
       0.05819449, 0.10684657, 0.02009897, 0.28287537, 0.05690489,
       0.23158255, 0.18562026, 0.02980003, 0.10969699, 0.09839723,
       0.11384071,        nan, 0.09842224, 0.14546998, 0.09575274,
       0.0311396 , 0.44334193, 0.17908437, 0.11692139, 0.28106214,
       0.01901531, 0.24379014, 2.41440295, 0.0403854 , 0.03046635,
       0.09177906, 0.13553143, 0.14199556, 0.12359483, 0.18016

In [51]:
simulation.cells.get_glv_coefficients()["interaction_estimates"]

array([[ 1.17311296e-01,  5.50435205e-17,  2.09962819e-16, ...,
        -1.62304019e-16,  5.58634878e-02,  3.20286999e-18],
       [-3.12079070e-19,  6.51324327e-02, -3.53145693e-02, ...,
         3.96982950e-03, -1.67390045e-01, -2.94304570e-03],
       [ 6.25924993e-20, -9.56975704e-03,  1.37298560e-01, ...,
        -1.19092403e-17, -7.10253615e-02,  3.22204284e-02],
       ...,
       [ 0.00000000e+00,  6.97869935e-07,  0.00000000e+00, ...,
        -6.49727625e-02,  0.00000000e+00,  0.00000000e+00],
       [ 4.72827916e-02, -3.90193072e-02, -2.01991422e-01, ...,
         0.00000000e+00,  1.07595125e-01,  2.93417511e-02],
       [ 0.00000000e+00,  1.36636080e-08,  4.47128186e-02, ...,
         0.00000000e+00,  5.27244332e-02,  1.48789074e-01]])