In [1]:
from glob import glob

filenames = sorted(list(glob('npzfiles/*.npz')))

In [2]:
import numpy as np
from simulations.concentrations.MLE import get_NB_score_function

from scipy.optimize import root_scalar

In [3]:
from analysis_utils.concentrations_MLE import get_NB_MLE

In [4]:
get_NB_MLE(filenames[0])

0

In [5]:
npzfile = np.load('concentration_ML_estimates/simulation.001.density.npz')

In [6]:
npzfile['whole_sim']

array([0.99728056])

In [7]:
npzfile['medium_batches']

array([0.97099466, 1.07846802, 0.91104759, 0.98618833, 0.99322316,
       0.98861283, 1.01219247, 0.96622176, 1.1521671 , 1.03763319,
       0.87166411, 1.00626979, 0.95756283, 1.07283983, 0.95409767,
       1.01989602, 0.95609192, 0.92729731, 1.06748984, 0.90898774,
       1.0027114 , 0.87179765, 1.18677232, 1.03119248, 1.15525489,
       0.96009543, 1.04374502, 0.94008329, 1.03812336, 1.01939324])

In [8]:
npzfile['small_batches']

array([0.82010776, 0.99470389, 1.30654147, ..., 1.22275219, 6.72699387,
              inf])

## Example

In [9]:
npzfile = np.load(filenames[0])
droplets = npzfile['droplets']

counts = np.sum(droplets, axis=1)
mean_count = np.mean(counts)
number_droplets, number_strains = droplets.shape

score_function = get_NB_score_function(counts, mean_count, number_droplets, number_strains)

In [10]:
from scipy.optimize import fsolve

`fsolve` more general framework/wrapper, but seem to get better results using more 'targeted' options

In [11]:
fsolve(score_function, 2, full_output=True)

(array([109506.54137136]),
 {'nfev': 56,
  'fjac': array([[-1.]]),
  'r': array([-2.94400003e-07]),
  'qtf': array([1.7717654e-09]),
  'fvec': array([-1.7717654e-09])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [12]:
root_scalar(f=score_function, x0=2, bracket=(0.00001,100000))

      converged: True
           flag: 'converged'
 function_calls: 35
     iterations: 34
           root: 0.9972805613295225

In [13]:
fsolve(score_function, 1, full_output=True)

(array([0.99728056]),
 {'nfev': 7,
  'fjac': array([[-1.]]),
  'r': array([74.43183023]),
  'qtf': array([-2.3865141e-09]),
  'fvec': array([-6.4028427e-10])},
 1,
 'The solution converged.')

In [14]:
fsolve(score_function, 0.5, full_output=True)

(array([0.99728056]),
 {'nfev': 13,
  'fjac': array([[-1.]]),
  'r': array([38.10366112]),
  'qtf': array([-5.18048182e-09]),
  'fvec': array([4.07453626e-10])},
 1,
 'The solution converged.')

In [15]:
fsolve(score_function, 1.5, full_output=True)

(array([-204227.75791615]),
 {'nfev': 54,
  'fjac': array([[-1.]]),
  'r': array([-2.98095484e-06]),
  'qtf': array([3.95055766e-10]),
  'fvec': array([-3.95055766e-10])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [16]:
fsolve(score_function, 1.75, full_output=True)

(array([136069.61734594]),
 {'nfev': 58,
  'fjac': array([[-1.]]),
  'r': array([-0.00010306]),
  'qtf': array([4.90613772e-10]),
  'fvec': array([-4.90613772e-10])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

In [17]:
root_scalar(f=score_function, x0=1.75, bracket=(0.0001,10000))

      converged: True
           flag: 'converged'
 function_calls: 27
     iterations: 26
           root: 0.9972805613266287

In [18]:
fsolve(score_function, 1.6, full_output=True)

(array([156116.17128334]),
 {'nfev': 45,
  'fjac': array([[-1.]]),
  'r': array([1.35247486e-05]),
  'qtf': array([3.32224026e-10]),
  'fvec': array([4.4408921e-16])},
 1,
 'The solution converged.')

In [19]:
root_scalar(f=score_function, x0=1.6, bracket=(0.0001,10000))

      converged: True
           flag: 'converged'
 function_calls: 27
     iterations: 26
           root: 0.9972805613266287

In [20]:
fsolve(score_function, 1.55, full_output=True)

(array([80543.2775406]),
 {'nfev': 64,
  'fjac': array([[-1.]]),
  'r': array([-2.30501327e-07]),
  'qtf': array([4.53993909e-09]),
  'fvec': array([-4.53993909e-09])},
 1,
 'The solution converged.')

In [21]:
root_scalar(f=score_function, x0=1.55, bracket=(0.0001,10000))

      converged: True
           flag: 'converged'
 function_calls: 27
     iterations: 26
           root: 0.9972805613266287

In [22]:
fsolve(score_function, 1.5, full_output=True)

(array([-204227.75791615]),
 {'nfev': 54,
  'fjac': array([[-1.]]),
  'r': array([-2.98095484e-06]),
  'qtf': array([3.95055766e-10]),
  'fvec': array([-3.95055766e-10])},
 5,
 'The iteration is not making good progress, as measured by the \n  improvement from the last ten iterations.')

#### score function evaluated at some values

In [23]:
score_function(0.5)

142.78805653203744

In [24]:
score_function(0.75)

21.773968398105353

In [25]:
score_function(0.8)

14.376065457763616

In [26]:
score_function(0.9)

5.0152851841412485

In [27]:
score_function(0.95)

2.078976527962368

In [28]:
score_function(0.975)

0.9075486527290195

In [29]:
score_function(1)

-0.10280788224190474

In [30]:
score_function(1.0010625)

-0.1425287437159568

In [31]:
score_function(1.003125)

-0.21892554697114974

In [32]:
score_function(1.00625)

-0.3329182585584931

In [33]:
score_function(1.0125)

-0.5546828377409838

In [34]:
score_function(1.025)

-0.9743641348322853

In [35]:
score_function(1.05)

-1.7260224765050225

In [36]:
score_function(1.1)

-2.9316813706536777

In [37]:
score_function(1.2)

-4.474512460292317

In [38]:
score_function(2)

-4.866960105049657

In [39]:
score_function(200)

-0.0009923995701228705

In [40]:
score_function(2000)

-9.97244268319264e-06

In [41]:
score_function(20000)

-9.987919469267581e-08

In [42]:
score_function(200000)

-1.3426577627484448e-09

In [43]:
score_function(2000000)

-1.376745439873872e-09

## Does this really work in general?

In [44]:
get_NB_MLE(filenames[17])

0

In [45]:
npzfile = np.load('concentration_ML_estimates/simulation.018.density.npz')

In [46]:
npzfile['whole_sim']

array([0.99891004])

In [47]:
npzfile['medium_batches']

array([0.85515805, 0.99772228, 1.04082493, 1.11478646, 0.9657881 ,
       0.99600618, 1.01312022, 1.02460732, 1.00478778, 0.95275498,
       0.87170618, 1.09988309, 1.07400711, 0.81201553, 1.19106015,
       0.97051787, 1.04098981, 1.09111069, 1.10842102, 0.97004656,
       1.23089968, 1.0454716 , 1.05313282, 1.00644341, 0.93778721,
       1.01278606, 0.9669823 , 0.8966052 , 0.90074283, 0.97151163])

In [48]:
npzfile['small_batches']

array([6.03984699, 1.58110974, 0.91603198, ..., 1.01146597, 0.73308521,
       1.16686156])